---BÀI 2

﻿	--a.Truy vấn cơ bản
	--1
	select MACT, HOTEN,SO,VITRI,NGAYSINH,DIACHI 
	from CAUTHU

	--2
	select MACT, HOTEN,SO,VITRI,NGAYSINH,DIACHI 
	from CAUTHU
	where  SO=7 and VITRI=N'Tiền vệ'

	--3
select TENHLV,NGAYSINH,DIACHI,DIENTHOAI 
from HUANLUYENVIEN

	--4
select MACT, HOTEN,SO,VITRI,NGAYSINH,DIACHI 
from CAULACBO,CAUTHU
where (CAUTHU.MACLB=CAULACBO.MACLB) and MAQG='VN' and TENCLB=N'Becamex Bình Dương'

	--5
select MACT,HOTEN,NGAYSINH,DIACHI,VITRI 
from CAUTHU,CAULACBO
where (CAULACBO.MACLB=CAUTHU.MACLB)
and TENCLB=N'SHB Đà Nẵng' and MAQG='BRA'

	--6
select MACT, HOTEN,SO,VITRI,NGAYSINH,CAUTHU.DIACHI 
from CAUTHU,CAULACBO,SANVD
where (CAULACBO.MACLB=CAUTHU.MACLB and CAULACBO.MASAN=SANVD.MASAN)
and SANVD.TENSAN=N'Sân Long An'

	--7
select MATRAN,NGAYTD,SANVD.TENSAN,clb1.TENCLB as TENCLB1, clb2.TENCLB as TENCLB2, KETQUA
from SANVD,CAULACBO clb1,CAULACBO clb2, TRANDAU
where (SANVD.MASAN=TRANDAU.MASAN and clb1.MACLB=TRANDAU.MACLB1 and clb2.MACLB=TRANDAU.MACLB2)
and TRANDAU.VONG=2 and TRANDAU.NAM=2009

	--8
select hlv.MAHLV, hlv.TENHLV,hlv.NGAYSINH, hlv.DIACHI, HLV_CLB.VAITRO, CAULACBO.TENCLB
from HUANLUYENVIEN hlv,CAULACBO, HLV_CLB
where (hlv.MAHLV=HLV_CLB.MAHLV and CAULACBO.MACLB=HLV_CLB.MACLB)
and hlv.MAQG='VN'
	
	--9
select top 3 TENCLB
from CAULACBO,BANGXH
where (CAULACBO.MACLB=BANGXH.MACLB) 
and VONG=3
order by BANGXH.DIEM desc

	--10
select hlv.MAHLV,TENHLV,hlv.NGAYSINH, hlv.DIACHI, VAITRO
from HUANLUYENVIEN hlv, CAULACBO clb, HLV_CLB
where (HLV_CLB.MACLB=clb.MACLB and HLV_CLB.MAHLV=hlv.MAHLV)
and clb.MATINH=N'BD'

--b
	--1
select TENCLB, COUNT( distinct MACT) as SO_CAU_THU 
from CAULACBO clb, CAUTHU ct
where (clb.MACLB=ct.MACLB)
group by TENCLB

	--2
select TENCLB, COUNT( distinct MACT) CAU_THU_NUOC_NGOAI
from CAULACBO clb, CAUTHU ct
where (clb.MACLB=ct.MACLB and ct.MAQG <>'VN')
group by TENCLB

	--3
select clb.MACLB, clb.TENCLB,svd.TENSAN, svd.DIACHI,result.SOLUONG
from CAULACBO clb, SANVD svd,
(
	select CAULACBO.MACLB, count(MACT) as SOLUONG
	from CAULACBO,CAUTHU,QUOCGIA
	where (CAULACBO.MACLB=CAUTHU.MACLB and CAUTHU.MAQG = QUOCGIA.MAQG and TENQG <>N'Việt Nam')
	group by CAULACBO.MACLB
	having count(MACT)>=2
)result
where clb.MACLB=result.MACLB and clb.MASAN=svd.MASAN

	--4
select TINH.TENTINH as TÊN_TỈNH, count(distinct MACT)
from TINH, CAUTHU ct,CAULACBO clb
where (TINH.MATINH=clb.MATINH and ct.MACLB=clb.MACLB)
and ct.VITRI=N'Tiền đạo'
group by TINH.TENTINH

	--5
select clb.TENCLB, TINH.TENTINH
from CAULACBO clb, TINH, BANGXH bxh
where (clb.MATINH=TINH.MATINH and clb.MACLB=bxh.MACLB)
and bxh.NAM=2009 and bxh.VONG=3
and DIEM >= all (select DIEM from BANGXH where VONG=3 and NAM=2009)

--c
	--1
select * 
from HUANLUYENVIEN hlv, HLV_CLB
where (hlv.MAHLV=HLV_CLB.MAHLV) 
and hlv.MAHLV in (select MAHLV from HLV_CLB)
and hlv.DIENTHOAI IS NULL

	--2
select * 
from HUANLUYENVIEN hlv, QUOCGIA qg
where (hlv.MAQG=qg.MAQG and qg.TENQG=N'Việt Nam')
and hlv.MAHLV not in (select MAHLV from HLV_CLB)

	--3

select ct.*
from CAUTHU ct
where (ct.MACLB in 
	(
		select MACLB 
		from BANGXH
		where VONG=3 and NAM=2009 and (HANG<3 or HANG>6)
	)
)

	--4
select td.*
from TRANDAU td, CAULACBO clb
where  (td.MACLB1=clb.MACLB or td.MACLB2=clb.MACLB) and
clb.MACLB in (select TOP 1 MACLB from BANGXH where VONG=3 order by DIEM desc )

---BÀI 3

--1a
SELECT 
	FORMAT (TRANDAU.NGAYTD, 'dd/MM/yyyy') AS 'Ngày thi đấu',
	CLB1.TENCLB AS 'Tên CLB1',
	CLB2.TENCLB AS 'Tên CLB2',
	TRANDAU.KETQUA AS 'Kết quả'
FROM
	CAULACBO CLB1 JOIN TRANDAU ON TRANDAU.MACLB1 = CLB1.MACLB
	JOIN CAULACBO CLB2 ON TRANDAU.MACLB2 = CLB2.MACLB
WHERE 
		MONTH (TRANDAU.NGAYTD) = 3
	AND
	(
		TRANDAU.MASAN = CLB1.MASAN AND (CAST(RIGHT(TRANDAU.KETQUA, 1) AS INT) = 0)
	OR 
		TRANDAU.MASAN = CLB2.MASAN AND (CAST(LEFT(TRANDAU.KETQUA, 1) AS INT) = 0)

		)
--2a
	SELECT MACT, HOTEN,VITRI, FORMAT(NGAYSINH, 'dd/MM/yyyy') as NGAYSINH
	FROM CAUTHU
	WHERE
		HOTEN LIKE N'% Công %'
--3a
	SELECT MACT, HOTEN,VITRI, FORMAT(NGAYSINH, 'dd/MM/yyyy') as NGAYSINH
	FROM CAUTHU
	WHERE
		HOTEN NOT LIKE N'Nguyễn %'
--4a
	SELECT 
	*
FROM
	HUANLUYENVIEN HLV JOIN QUOCGIA QG ON HLV.MAQG = QG.MAQG
WHERE
		QG.TENQG LIKE N'Việt Nam'
	AND
		(YEAR(CURRENT_TIMESTAMP) - YEAR(HLV.NGAYSINH) ) >35 
	AND (YEAR(GETDATE()) - YEAR(HLV.NGAYSINH) ) <40 

--5a
	SELECT hlv.MAHLV, HLV.NGAYSINH, HLV.TENHLV, HLV.DIACHI
	FROM CAULACBO CLB JOIN HLV_CLB ON(CLB.MACLB=HLV_CLB.MACLB)
		JOIN HUANLUYENVIEN HLV ON(HLV_CLB.MAHLV=HLV.MAHLV)
	WHERE
		HLV_CLB.VAITRO LIKE N'HLV Chính'
	AND
		DAY(HLV.NGAYSINH)=20
	AND 
		MONTH(HLV.NGAYSINH)=5
--6a
	SELECT CLB.MACLB,T.TENTINH
	FROM CAULACBO CLB JOIN TINH T ON(CLB.MATINH=T.MATINH)
		JOIN(SELECT TOP (1) SUM(CAST(LEFT(BANGXH.HIEUSO, 1) AS INT)) AS BANTHANG, MACLB
		FROM 
			BANGXH
		WHERE
			VONG =3
		GROUP BY 
			MACLB
		ORDER BY 
			BANTHANG DESC) temp 
		ON(CLB.MACLB=temp.MACLB)
--1b
	SELECT 
	COUNT (*) AS NUM_CTNN, MACLB
INTO 
	TEMP_B1
FROM
	CAUTHU JOIN QUOCGIA ON CAUTHU.MAQG = QUOCGIA.MAQG
WHERE
	QUOCGIA.TENQG NOT LIKE N'Việt Nam'
GROUP BY
	CAUTHU.MACLB

SELECT
	CAULACBO.MACLB AS 'Mã CLB',
	CAULACBO.TENCLB AS 'Tên CLB',
	SANVD.TENSAN AS 'Tên Sân',
	SANVD.DIACHI AS 'Địa chỉ',
	TEMP_B1.NUM_CTNN AS 'Số CTNN'
FROM
	CAULACBO JOIN SANVD ON CAULACBO.MASAN = SANVD.MASAN
	JOIN TEMP_B1 ON CAULACBO.MACLB = TEMP_B1.MACLB
WHERE
	TEMP_B1.NUM_CTNN > 1
--2b
	SELECT TOP(1) (SUM(CAST(LEFT(BXH.HIEUSO,1) AS INT))-SUM(CAST(RIGHT(BXH.HIEUSO,1) AS INT))) AS HIEUSO,CLB.MACLB 
	INTO TEMP_2B_1
	FROM CAULACBO CLB JOIN BANGXH BXH ON(CLB.MACLB=BXH.MACLB)
	WHERE BXH.VONG=4
	GROUP BY CLB.MACLB
	ORDER BY (HIEUSO) DESC

	SELECT CLB.TENCLB,TINH.TENTINH
	FROM CAULACBO CLB JOIN TINH ON(CLB.MATINH=TINH.MATINH)
		JOIN TEMP_2B_1 ON(CLB.MACLB=TEMP_2B_1.MACLB)
--3b
	SELECT TOP(1) BXH.HANG, CLB.MACLB
	INTO TEMP_3B
	FROM CAULACBO CLB JOIN BANGXH BXH ON(CLB.MACLB=BXH.MACLB)
	WHERE BXH.VONG=3
	ORDER BY (HANG) DESC

	SELECT TD.*
	FROM TRANDAU TD JOIN CAULACBO CLB ON(TD.MACLB1=CLB.MACLB OR TD.MACLB2=CLB.MACLB)
		JOIN TEMP_3B ON(TEMP_3B.MACLB=CLB.MACLB)
--4B
	CREATE FUNCTION fn_4B (@MaCLB varchar(5))
	RETURNS TABLE AS RETURN
	( SELECT DISTINCT MACLB FROM
		(SELECT MACLB1 as MACLB FROM TRANDAU WHERE MACLB2 = @MaCLB) as table1 UNION
		(SELECT MACLB2 as MACLB FROM TRANDAU WHERE MACLB1 = @MaCLB)
	);

	SELECT CAULACBO.MACLB, CAULACBO.TENCLB
	FROM CAULACBO
	WHERE (SELECT COUNT (*) FROM fn_4B(MACLB)) = (SELECT COUNT (*) - 1 FROM CAULACBO)
		
--5B
	SELECT CAULACBO.MACLB, CAULACBO.TENCLB
	FROM CAULACBO
	WHERE (SELECT COUNT (*)
	   FROM TRANDAU
	   WHERE MACLB1 = MACLB) = (SELECT COUNT (*) - 1 FROM CAULACBO)
--1C
	CREATE RULE CHECKVITRI
	as @VITRI in (N'Thủ môn', N'Tiền đạo', N'Tiền vệ', N'Trung vệ', N'Hậu vệ');

	EXEC sp_bindrule 'CHECKVITRI', 'CAUTHU.VITRI';

	DROP RULE CHECKVITRI
--2C
	ALTER TABLE HLV_CLB
	ADD CONSTRAINT CHECKHLV
		CHECK(VAITRO IN (N'HLV chính', N'HLV phụ', N'HLV thể lực', N'HLV thủ môn'))

	ALTER TABLE HLV_CLB
	DROP CONSTRAINT CHECKHLV
--3C
	CREATE RULE CHECKTUOI
	AS (YEAR(GETDATE())-YEAR(@NGAYSINH)>=18);

	EXEC sp_bindrule 'CHECKTUOI','CAUTHU.NGAYSINH';

	DROP RULE CHECKTUOI
--4C
	ALTER TABLE TRANDAU
		ADD CONSTRAINT CHECKKETQUA
			CHECK(KETQUA LIKE '[0-9]-[0-9]')

	ALTER TABLE TRANDAU
		DROP CONSTRAINT CHECKKETQUA

--1D
	CREATE VIEW D1 AS
		SELECT CT.HOTEN,ct.NGAYSINH,ct.DIACHI,ct.SO,ct.VITRI
		FROM CAUTHU CT JOIN CAULACBO CLB ON(CT.MACLB=CLB.MACLB)
			JOIN QUOCGIA QG ON(QG.MAQG=CT.MAQG)
		WHERE (CLB.TENCLB=N'SHB Đà Nẵng') and TENQG=N'Bra-xin'

	DROP VIEW D1

	select* from D1
--2D
	CREATE VIEW D2 as
	SELECT MATRAN, NGAYTD, TENSAN, clb1.TENCLB as TENCLB1, clb2.TENCLB as TENCLB2, KETQUA
	FROM TRANDAU INNER JOIN SANVD
	ON TRANDAU.MASAN = SANVD.MASAN INNER JOIN CAULACBO as clb1
	ON TRANDAU.MACLB1 = clb1.MACLB INNER JOIN CAULACBO as clb2
	ON TRANDAU.MACLB2 = clb2.MACLB
	WHERE VONG = 3;

DROP VIEW D2
--3D
	CREATE VIEW v_hlv as
	SELECT HUANLUYENVIEN.MAHLV, TENHLV, NGAYSINH, DIACHI
	FROM HUANLUYENVIEN INNER JOIN HLV_CLB
	ON HUANLUYENVIEN.MAHLV = HLV_CLB.MAHLV INNER JOIN QUOCGIA
	ON HUANLUYENVIEN.MAQG = QUOCGIA.MAQG
	WHERE QUOCGIA.TENQG LIKE N'%Việt Nam%';

DROP VIEW v_hlv
--4D
CREATE VIEW D4 as
	SELECT CAULACBO.MACLB, TENCLB, SANVD.DIACHI, COUNT(TENCLB) as 'Số lượng cầu thủ'
	FROM CAUTHU inner join CAULACBO
	on CAUTHU.MACLB = CAULACBO.MACLB
	inner join QUOCGIA
	on CAUTHU.MAQG = QUOCGIA.MAQG
	inner join SANVD
	on CAULACBO.MASAN = SANVD.MASAN
	where QUOCGIA.TENQG NOT LIKE N'%Việt Nam%'
	GROUP BY TENCLB, CAULACBO.MACLB, SANVD.DIACHI
	HAVING COUNT(TENCLB) >= 2;

DROP VIEW D4


--5D
	CREATE VIEW 5D as
	SELECT TENTINH, COUNT(HOTEN) as N'Số cầu thủ'
	FROM CAULACBO INNER JOIN TINH
	ON CAULACBO.MATINH = TINH.MATINH INNER JOIN CAUTHU
	ON CAULACBO.MACLB = CAUTHU.MACLB
	WHERE CAUTHU.VITRI LIKE N'%Tiền đạo%'
	GROUP BY TINH.TENTINH;

DROP VIEW 5D
--6D
	CREATE VIEW D6 AS
	SELECT CLB.TENCLB,TINH.TENTINH
	FROM CAULACBO CLB JOIN BANGXH BXH ON(CLB.MACLB=BXH.MACLB)
		JOIN TINH ON(CLB.MATINH=TINH.MATINH)
	WHERE BXH.HANG=1 AND VONG=3
 
	DROP VIEW D6
--7D
	CREATE VIEW D7 as
	SELECT TENHLV
	FROM HUANLUYENVIEN
	WHERE DIENTHOAI = null AND MAHLV IN (SELECT MAHLV
										FROM HLV_CLB);

DROP VIEW D7;

--8D
CREATE VIEW D8 as
	SELECT HUANLUYENVIEN.TENHLV
	FROM HUANLUYENVIEN INNER JOIN QUOCGIA
	ON HUANLUYENVIEN.MAQG = QUOCGIA.MAQG
	WHERE QUOCGIA.TENQG LIKE N'%Việt Nam%' AND  
		HUANLUYENVIEN.MAHLV NOT IN (SELECT MAHLV
									FROM HLV_CLB);

DROP VIEW D8;

--9D
	CREATE VIEW D9 as
	SELECT MACLB1, MACLB2, YEAR(NGAYTD) as 'NAM' , VONG, CAST(LEFT(KETQUA, CHARINDEX('-', KETQUA, 1) - 1) AS INT) AS 'SOBANTHANG',
					CAST(RIGHT(KETQUA, LEN(KETQUA) - CHARINDEX('-', KETQUA, 1)) as INT) AS 'SOBANTHUA'
	FROM TRANDAU
	
	DROP VIEW D9
--10D
	CREATE VIEW d10 as
	SELECT MACLB1 as MACLB, YEAR(NGAYTD) as 'NAM' , VONG, CAST(LEFT(KETQUA, CHARINDEX('-', KETQUA, 1) - 1) AS INT) AS 'SOBANTHANG',
					CAST(RIGHT(KETQUA, LEN(KETQUA) - CHARINDEX('-', KETQUA, 1)) as INT) AS 'SOBANTHUA'
	FROM TRANDAU;

	DROP VIEW D10
--11D
CREATE VIEW v_cau11 as
SELECT MACLB2 as MACLB, YEAR(NGAYTD) as 'NAM' , VONG, CAST(LEFT(KETQUA, CHARINDEX('-', KETQUA, 1) - 1) AS INT) AS 'SOBANTHANG',
					CAST(RIGHT(KETQUA, LEN(KETQUA) - CHARINDEX('-', KETQUA, 1)) as INT) AS 'SOBANTHUA'
	FROM TRANDAU;
--12D
CREATE VIEW D12
	SELECT td.*
	FROM CAULACBO CLB JOIN BANGXH BXH ON(CLB.MACLB=BXH.MACLB) 
		JOIN TRANDAU TD ON(TD.MACLB1=CLB.MACLB OR TD.MACLB2=CLB.MACLB)
	WHERE 
		BXH.HANG=1 and BXH.VONG=3

		DROP VIEW D12
--13D
CREATE VIEW v_cau13 as
SELECT NGAYTD, TENSAN, clb1.TENCLB as 'TENCLB1', clb2.TENCLB as 'TENCLB2', KETQUA
FROM TRANDAU INNER JOIN CAULACBO as clb1 ON TRANDAU.MACLB1 = clb1.MACLB
INNER JOIN CAULACBO AS clb2 ON TRANDAU.MACLB2 = clb2.MACLB
INNER JOIN SANVD ON TRANDAU.MASAN = SANVD.MASAN
WHERE clb1.MACLB = (SELECT TOP 1 MACLB 
					FROM BANGXH
					WHERE VONG = 3
					ORDER BY HANG DESC)
   OR clb2.MACLB = (SELECT TOP 1 MACLB 
					FROM BANGXH
					WHERE VONG = 3
					ORDER BY HANG DESC)

DROP VIEW D13